FROM oven/bun:1.4.0 AS build
WORKDIR /app

COPY package.json bun.lock bunfig.toml turbo.json ./
COPY apps ./apps
COPY packages ./packages

RUN bun install --frozen-lockfile
RUN bun turbo run build --filter=@mavry/api...

ENV NODE_ENV=production
EXPOSE 4040
CMD ["bun", "run", "--cwd", "apps/api", "prod"]
